// Generated by gencpp from file plumbing_srv/ADDINTS.msg
// DO NOT EDIT!


#ifndef PLUMBING_SRV_MESSAGE_ADDINTS_H
#define PLUMBING_SRV_MESSAGE_ADDINTS_H

#include <ros/service_traits.h>


#include <plumbing_srv/ADDINTSRequest.h>
#include <plumbing_srv/ADDINTSResponse.h>


namespace plumbing_srv
{

struct ADDINTS
{

typedef ADDINTSRequest Request;
typedef ADDINTSResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ADDINTS
} // namespace plumbing_srv


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::plumbing_srv::ADDINTS > {
  static const char* value()
  {
    return "4781436a0c2affec8025955a6041e481";
  }

  static const char* value(const ::plumbing_srv::ADDINTS&) { return value(); }
};

template<>
struct DataType< ::plumbing_srv::ADDINTS > {
  static const char* value()
  {
    return "plumbing_srv/ADDINTS";
  }

  static const char* value(const ::plumbing_srv::ADDINTS&) { return value(); }
};


// service_traits::MD5Sum< ::plumbing_srv::ADDINTSRequest> should match
// service_traits::MD5Sum< ::plumbing_srv::ADDINTS >
template<>
struct MD5Sum< ::plumbing_srv::ADDINTSRequest>
{
  static const char* value()
  {
    return MD5Sum< ::plumbing_srv::ADDINTS >::value();
  }
  static const char* value(const ::plumbing_srv::ADDINTSRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::plumbing_srv::ADDINTSRequest> should match
// service_traits::DataType< ::plumbing_srv::ADDINTS >
template<>
struct DataType< ::plumbing_srv::ADDINTSRequest>
{
  static const char* value()
  {
    return DataType< ::plumbing_srv::ADDINTS >::value();
  }
  static const char* value(const ::plumbing_srv::ADDINTSRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::plumbing_srv::ADDINTSResponse> should match
// service_traits::MD5Sum< ::plumbing_srv::ADDINTS >
template<>
struct MD5Sum< ::plumbing_srv::ADDINTSResponse>
{
  static const char* value()
  {
    return MD5Sum< ::plumbing_srv::ADDINTS >::value();
  }
  static const char* value(const ::plumbing_srv::ADDINTSResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::plumbing_srv::ADDINTSResponse> should match
// service_traits::DataType< ::plumbing_srv::ADDINTS >
template<>
struct DataType< ::plumbing_srv::ADDINTSResponse>
{
  static const char* value()
  {
    return DataType< ::plumbing_srv::ADDINTS >::value();
  }
  static const char* value(const ::plumbing_srv::ADDINTSResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PLUMBING_SRV_MESSAGE_ADDINTS_H
