// Generated by gencpp from file plumbing_srv/AddInts.msg
// DO NOT EDIT!


#ifndef PLUMBING_SRV_MESSAGE_ADDINTS_H
#define PLUMBING_SRV_MESSAGE_ADDINTS_H

#include <ros/service_traits.h>


#include <plumbing_srv/AddIntsRequest.h>
#include <plumbing_srv/AddIntsResponse.h>


namespace plumbing_srv
{

struct AddInts
{

typedef AddIntsRequest Request;
typedef AddIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddInts
} // namespace plumbing_srv


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::plumbing_srv::AddInts > {
  static const char* value()
  {
    return "4781436a0c2affec8025955a6041e481";
  }

  static const char* value(const ::plumbing_srv::AddInts&) { return value(); }
};

template<>
struct DataType< ::plumbing_srv::AddInts > {
  static const char* value()
  {
    return "plumbing_srv/AddInts";
  }

  static const char* value(const ::plumbing_srv::AddInts&) { return value(); }
};


// service_traits::MD5Sum< ::plumbing_srv::AddIntsRequest> should match
// service_traits::MD5Sum< ::plumbing_srv::AddInts >
template<>
struct MD5Sum< ::plumbing_srv::AddIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::plumbing_srv::AddInts >::value();
  }
  static const char* value(const ::plumbing_srv::AddIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::plumbing_srv::AddIntsRequest> should match
// service_traits::DataType< ::plumbing_srv::AddInts >
template<>
struct DataType< ::plumbing_srv::AddIntsRequest>
{
  static const char* value()
  {
    return DataType< ::plumbing_srv::AddInts >::value();
  }
  static const char* value(const ::plumbing_srv::AddIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::plumbing_srv::AddIntsResponse> should match
// service_traits::MD5Sum< ::plumbing_srv::AddInts >
template<>
struct MD5Sum< ::plumbing_srv::AddIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::plumbing_srv::AddInts >::value();
  }
  static const char* value(const ::plumbing_srv::AddIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::plumbing_srv::AddIntsResponse> should match
// service_traits::DataType< ::plumbing_srv::AddInts >
template<>
struct DataType< ::plumbing_srv::AddIntsResponse>
{
  static const char* value()
  {
    return DataType< ::plumbing_srv::AddInts >::value();
  }
  static const char* value(const ::plumbing_srv::AddIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PLUMBING_SRV_MESSAGE_ADDINTS_H
